/** @format */

export const SliderData = [
  {
    title: 'St. Joseph, Missouri',
    price: 'October 2021',
    path: '/homes',
    label: '',
    image: 'https://i.ibb.co/MPJ9zdD/us-1.jpg',
    alt: 'House',
  },
  {
    title: 'St. Joseph, Missouri',
    price: 'October 2021',
    path: '/homes',
    label: '',
    image: 'https://i.ibb.co/gtJTF4C/us-2.jpg',
    alt: 'House',
  },
  {
    title: 'St. Joseph, Missouri',
    price: 'October 2021',
    path: '/homes',
    label: '',
    image: 'https://i.ibb.co/syBLWPG/us-3.jpg',
    alt: 'House',
  },
  {
    title: 'St. Joseph, Missouri',
    price: 'October 2021',
    path: '/homes',
    label: '',
    image: 'https://i.ibb.co/JCFSR5x/us-4.jpg',
    alt: 'House',
  },
  {
    title: 'St. Joseph, Missouri',
    price: 'October 2021',
    path: '/homes',
    label: '',
    image: 'https://i.ibb.co/16WRS9s/us-5.jpg',
    alt: 'House',
  },
  {
    title: 'St. Joseph, Missouri',
    price: 'October 2021',
    path: '/homes',
    label: '',
    image: 'https://i.ibb.co/QHpqTtd/us-6.jpg',
    alt: 'House',
  },
  {
    title: 'St. Joseph, Missouri',
    price: 'October 2021',
    path: '/homes',
    label: '',
    image: 'https://i.ibb.co/Q8RW94M/us-7.jpg',
    alt: 'House',
  },
  {
    title: 'St. Joseph, Missouri',
    price: 'October 2021',
    path: '/homes',
    label: '',
    image: 'https://i.ibb.co/C650Dpf/us-8.jpg',
    alt: 'House',
  },
  {
    title: 'St. Joseph, Missouri',
    price: 'October 2021',
    path: '/homes',
    label: '',
    image: 'https://i.ibb.co/xqP09Y9/us-9.jpg',
    alt: 'House',
  },
  {
    title: 'St. Joseph, Missouri',
    price: 'October 2021',
    path: '/homes',
    label: '',
    image: 'https://i.ibb.co/4dpMnRh/us-10.jpg',
    alt: 'House',
  },
  {
    title: 'Monterrey, Mexico',
    price: 'November 2021',
    path: '/homes',
    label: '',
    image: ' https://i.ibb.co/SDkWjrs/us-12.jpg',
    alt: 'House',
  },
  {
    title: 'Panama City Beach, Florida',
    price: 'October 2021',
    path: '/homes',
    label: '',
    image: 'https://i.ibb.co/3hjh1n4/us-13.jpg',
    alt: 'House',
  },
  {
    title: 'Long Island, New York',
    price: 'October 2021',
    path: '/homes',
    label: '',
    image: 'https://i.ibb.co/4d0VGBP/us-11.jpg',
    alt: 'House',
  },
  {
    title: 'Querétaro, Mexico',
    price: 'November 2021',
    path: '/homes',
    label: '',
    image: 'https://i.ibb.co/RhpPDwN/us-19.jpg',
    alt: 'House',
  },
  {
    title: 'Random Forest, Arkansas',
    price: 'September 2021',
    path: '/homes',
    label: '',
    image: 'https://i.ibb.co/XkgnRdw/us-18.jpg',
    alt: 'House',
  },
];
